# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Snapshot Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup Node.js
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '16.x'
    -
      name: Build
      run: |
        npm ci
        npm run build
    -
      name: Upload snapshot
      if: success()
      uses: actions/upload-artifact@v3.1.0
      with:
        name: snapshot
        path: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
